const express=require('express');const crypto=require('crypto');const prisma=require('../prisma');const {saveDataUrl}=require('../fileStorage');const {requireAuth,requireRole,EDITOR_ROLES}=require('../middleware/auth');const {signToken}=require('../token');const logger=require('../logger');
const router=express.Router();router.use(requireAuth);
const MAX=12*1024*1024;const PREFIX=['data:application/pdf;base64,','data:image/jpeg;base64,','data:image/png;base64,','data:image/webp;base64,','data:application/msword;base64,','data:application/vnd.openxmlformats-officedocument.wordprocessingml.document;base64,','data:application/vnd.ms-excel;base64,','data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,'];const valid=v=>v==null||(typeof v==='string'&&v.length<=MAX&&PREFIX.some(p=>v.startsWith(p)));const dateOnly=v=>v==null?null:v.toISOString().slice(0,10);const serialize=r=>r?({...r,tanggal:dateOnly(r.tanggal),tanggal_selesai:dateOnly(r.tanggal_selesai),stage2_invoice_date:dateOnly(r.stage2_invoice_date),stage2_ls_date:dateOnly(r.stage2_ls_date),stage1_hps:r.stage1_hps==null?r.stage1_hps:Number(r.stage1_hps),stage2_invoice_amount:r.stage2_invoice_amount==null?r.stage2_invoice_amount:Number(r.stage2_invoice_amount),pic:r.createdBy?.nama_lengkap||null,createdBy:undefined,updatedBy:undefined}):r;
function kode(){return `PGD-${new Date().getFullYear()}-${crypto.randomInt(1000,10000)}`;}
router.get('/',async(req,res)=>{try{const {status,kategori,lokasi,search}=req.query;for(const [k,v] of Object.entries(req.query))if(!['status','kategori','lokasi','search'].includes(k)||typeof v!=='string'||v.length>150)return res.status(400).json({message:'Parameter filter tidak valid.'});const where={};if(status)where.status=status;if(kategori)where.kategori={equals:kategori,mode:'insensitive'};if(lokasi)where.lokasi={equals:lokasi,mode:'insensitive'};if(search)where.OR=[{nama_barang_jasa:{contains:search,mode:'insensitive'}},{kode:{contains:search,mode:'insensitive'}}];const rows=await prisma.pengadaan.findMany({where,include:{createdBy:{select:{nama_lengkap:true}}},orderBy:{created_at:'desc'}});res.json({data:rows.map(serialize)});}catch(err){logger.error('GET pengadaan gagal',{error:err});res.status(500).json({message:'Gagal mengambil data pengadaan.',error_code:err.code||'DB_ERROR'});}});
router.get('/:id',async(req,res)=>{try{const row=await prisma.pengadaan.findUnique({where:{id:Number(req.params.id)}});if(!row)return res.status(404).json({message:'Data tidak ditemukan.'});res.json({data:serialize(row)});}catch(err){res.status(500).json({message:'Gagal mengambil data.'});}});
router.post('/',async(req,res)=>{try{const {nama_barang_jasa,kategori,lokasi,titik_lokasi,metode_pengadaan,deskripsi,tanggal,request_document_name,request_document_file_data}=req.body;if(!nama_barang_jasa)return res.status(400).json({message:'Nama barang/jasa wajib diisi.'});if(request_document_file_data!==undefined&&!valid(request_document_file_data))return res.status(400).json({message:'Dokumen permintaan tidak valid.'});const path=request_document_file_data?await saveDataUrl(request_document_file_data,request_document_name,'pengadaan'):null;const row=await prisma.pengadaan.create({data:{kode:kode(),nama_barang_jasa,kategori:kategori||null,lokasi:lokasi||null,titik_lokasi:titik_lokasi||null,metode_pengadaan:metode_pengadaan||null,deskripsi:deskripsi||null,tanggal:tanggal?new Date(`${tanggal}T00:00:00Z`):new Date(),request_document_name:request_document_name||null,request_document_file_data:request_document_file_data||null,request_document_file_path:path,created_by:req.user.id}});
 // Karyawan yang membuat pengadaan otomatis dipromosikan jadi PIC atas pengadaan itu sendiri.
 let promotion=null;
 if(req.user.role==='karyawan'){
   const updatedUser=await prisma.user.update({where:{id:req.user.id},data:{role:'pic'}});
   promotion={token:signToken(updatedUser),user:{id:updatedUser.id,nama_lengkap:updatedUser.nama_lengkap,email:updatedUser.email,no_hp:updatedUser.no_hp,unit_kerja:updatedUser.unit_kerja,role:updatedUser.role}};
 }
 res.status(201).json({data:serialize(row),...(promotion||{})});
}catch(err){logger.error('POST pengadaan gagal',{error:err});res.status(500).json({message:'Gagal membuat pengadaan.'});}});
router.put('/:id',requireRole(EDITOR_ROLES),async(req,res)=>{try{const id=Number(req.params.id);if(!Number.isInteger(id))return res.status(400).json({message:'ID tidak valid.'});
 if(req.user.role==='pic'){
   const existing=await prisma.pengadaan.findUnique({where:{id},select:{created_by:true}});
   if(!existing)return res.status(404).json({message:'Data tidak ditemukan.'});
   if(existing.created_by!==req.user.id)return res.status(403).json({message:'Anda hanya dapat mengedit data pengadaan yang Anda tambahkan sendiri.'});
 }
 const body={...req.body};if(body.status==='selesai'&&!body.tanggal_selesai)body.tanggal_selesai=new Date().toISOString().slice(0,10);if(body.status&&body.status!=='selesai'&&body.tanggal_selesai===undefined)body.tanggal_selesai=null;for(const f of ['request_document_file_data','stage2_invoice_file_data','stage2_payment_proof_file_data','stage3_final_document_file_data','stage2_invoice_document_file_data'])if(body[f]!==undefined&&!valid(body[f]))return res.status(400).json({message:'Dokumen tidak valid.'});if(body.request_document_file_data)body.request_document_file_path=await saveDataUrl(body.request_document_file_data,body.request_document_name,'pengadaan');if(body.stage2_invoice_file_data)body.stage2_invoice_file_path=await saveDataUrl(body.stage2_invoice_file_data,body.stage2_invoice_document_name||body.stage2_invoice_number,'pengadaan');if(body.stage2_payment_proof_file_data)body.stage2_payment_proof_file_path=await saveDataUrl(body.stage2_payment_proof_file_data,body.stage2_payment_proof_name,'pengadaan');if(body.stage3_final_document_file_data)body.stage3_final_document_file_path=await saveDataUrl(body.stage3_final_document_file_data,body.stage3_final_document_name,'pengadaan');if(body.stage2_invoice_document_file_data)body.stage2_invoice_document_file_path=await saveDataUrl(body.stage2_invoice_document_file_data,body.stage2_invoice_document_name,'pengadaan');
 if(body.stage2_payment_number!==undefined&&body.stage2_payment_number!==null&&body.stage2_payment_number!==''){const n=Number(body.stage2_payment_number);if(!Number.isInteger(n)||n<1||n>20)return res.status(400).json({message:'Nomor GUP/TUP tidak valid (1-20).'});}
 const allowed=['nama_barang_jasa','kategori','lokasi','titik_lokasi','metode_pengadaan','nilai_hps','deskripsi','request_document_name','request_document_file_data','request_document_file_path','stage2_payment_method','stage2_payment_number','stage2_ls_date','stage2_vendor','stage2_invoice_number','stage2_invoice_date','stage2_invoice_amount','tanggal','status','tanggal_selesai','tahap1_status','tahap2_status','tahap3_status','stage2_invoice_document_name','stage2_invoice_document_file_data','stage2_invoice_document_file_path','stage2_invoice_file_data','stage2_invoice_file_path','stage2_payment_proof_name','stage2_payment_proof_file_data','stage2_payment_proof_file_path','stage3_final_document_name','stage3_final_document_file_data','stage3_final_document_file_path','catatan'];
 const DATE_FIELDS=['tanggal','tanggal_selesai','stage2_invoice_date','stage2_ls_date'];
 const data={};for(const f of allowed){if(body[f]===undefined)continue;if(DATE_FIELDS.includes(f))data[f]=body[f]?new Date(`${String(body[f]).slice(0,10)}T00:00:00Z`):null;else if(f==='stage2_payment_number')data[f]=body[f]===''||body[f]==null?null:Number(body[f]);else data[f]=body[f];}
 data.updated_by=req.user.id;const row=await prisma.pengadaan.update({where:{id},data});res.json({data:serialize(row)});}catch(err){logger.error('PUT pengadaan gagal',{error:err});if(err.code==='P2025')return res.status(404).json({message:'Data tidak ditemukan.'});res.status(500).json({message:'Gagal memperbarui data pengadaan.'});}});
router.delete('/:id',requireRole(EDITOR_ROLES),async(req,res)=>{try{
 const id=Number(req.params.id);
 if(req.user.role==='pic'){
   const existing=await prisma.pengadaan.findUnique({where:{id},select:{created_by:true}});
   if(!existing)return res.status(404).json({message:'Data tidak ditemukan.'});
   if(existing.created_by!==req.user.id)return res.status(403).json({message:'Anda hanya dapat menghapus data pengadaan yang Anda tambahkan sendiri.'});
 }
 await prisma.pengadaan.delete({where:{id}});res.json({message:'Data berhasil dihapus.'});
}catch(err){if(err.code==='P2025')return res.status(404).json({message:'Data tidak ditemukan.'});res.status(500).json({message:'Gagal menghapus data.'});}});module.exports=router;
