const express=require('express');const {EventEmitter}=require('events');const prisma=require('../prisma');const {saveDataUrl}=require('../fileStorage');const {requireAuth,requireRole,EDITOR_ROLES}=require('../middleware/auth');const {requireNotInMaintenance}=require('../middleware/maintenance');const logger=require('../logger');
const router=express.Router();
// Bus internal untuk broadcast SSE (Server-Sent Events) tiap ada booking berubah,
// supaya kalender publik & admin refresh real-time tanpa polling.
const bus=new EventEmitter();bus.setMaxListeners(0);
const broadcastChange=()=>bus.emit('change');
const STATUS=['belum','ditinjau','diterima'];
const ROOMS=['SERBAGUNA','SETJEN II','TRI DHARMA','BIRO UMUM','GRAHA KEMNAKER'];
const PREFIX=['data:application/pdf;base64,','data:image/jpeg;base64,','data:image/png;base64,'];
const validFile=v=>v==null||v===''||(typeof v==='string'&&v.length<=8*1024*1024&&PREFIX.some(p=>v.startsWith(p)));
const validText=(v,m)=>typeof v==='string'&&v.trim().length>0&&v.length<=m;
const validPhone=v=>typeof v==='string'&&/^[0-9+()\- .]{6,30}$/.test(v.trim());
const date=v=>new Date(`${v}T00:00:00Z`); const time=v=>new Date(`1970-01-01T${v}:00Z`);
const out=r=>({...r,date:r.booking_date.toISOString().slice(0,10),start:r.start_time.toISOString().slice(11,16),end:r.end_time.toISOString().slice(11,16),title:r.agenda,status:r.surat_status,updated_by_name:r.updatedBy?.nama_lengkap||null,updatedBy:undefined});
const publicSelect={id:true,agenda:true,room:true,pic:true,pic_phone:true,booking_date:true,start_time:true,end_time:true,surat_status:true};

// Public read-only schedule. No token required and only schedule information is returned.
router.get('/public-schedule',async(req,res)=>{try{const rows=await prisma.ruangRapat.findMany({select:publicSelect,orderBy:[{booking_date:'asc'},{start_time:'asc'},{id:'asc'}]});res.json({data:rows.map(out)});}catch(err){logger.error('GET public ruang rapat gagal',{error:err});res.status(500).json({message:'Gagal mengambil jadwal ruang rapat.'});}});

// SSE stream: cuma sinyal "ada perubahan" (bukan data booking itu sendiri),
// jadi aman dibuat publik -- browser EventSource native tidak bisa kirim
// header Authorization, dan data asli tetap lewat endpoint ber-otentikasi
// (GET '/') atau publik terbatas (GET '/public-schedule') seperti biasa.
router.get('/stream',(req,res)=>{
  res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','Connection':'keep-alive'});
  res.write('retry: 3000\n\n');
  const send=()=>{try{res.write(`data: ${Date.now()}\n\n`);}catch{}};
  bus.on('change',send);
  const heartbeat=setInterval(()=>{try{res.write(': heartbeat\n\n');}catch{}},25000);
  req.on('close',()=>{clearInterval(heartbeat);bus.off('change',send);});
});

router.use(requireAuth);
router.use(requireNotInMaintenance('ruang-rapat'));
router.get('/',async(req,res)=>{try{const rows=await prisma.ruangRapat.findMany({include:{updatedBy:{select:{nama_lengkap:true}}},orderBy:[{booking_date:'asc'},{start_time:'asc'},{id:'asc'}]});res.json({data:rows.map(out)});}catch(err){logger.error('GET ruang rapat gagal',{error:err});res.status(500).json({message:'Gagal mengambil jadwal ruang rapat.'});}});
router.post('/',requireRole(EDITOR_ROLES),async(req,res)=>{try{const {title,room,pic,pic_phone,date:startDate,start,end,status,surat_name,surat_file_data}=req.body;if(!validText(title,255)||!validText(room,150)||!validText(pic,150)||!validPhone(pic_phone)||!/^[0-9+()\- .]{6,30}$/.test(pic_phone.trim())||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(startDate)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(start)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(end))return res.status(400).json({message:'Data booking atau nomor HP PIC tidak valid.'});if(!ROOMS.includes(room)||!STATUS.includes(status||'belum')||!validFile(surat_file_data))return res.status(400).json({message:'Ruangan, status, atau surat tidak valid.'});if(start>=end)return res.status(400).json({message:'Jam selesai harus lebih besar dari jam mulai.'});const bookingDate=date(startDate);const conflict=await prisma.ruangRapat.findFirst({where:{room,booking_date:bookingDate,start_time:{lt:time(end)},end_time:{gt:time(start)}}});if(conflict)return res.status(409).json({message:'Ruangan sudah dibooking pada waktu tersebut.'});const path=surat_file_data?await saveDataUrl(surat_file_data,surat_name,'ruang-rapat'):null;const row=await prisma.ruangRapat.create({data:{agenda:title.trim(),room,pic:pic.trim(),pic_phone:pic_phone.trim(),booking_date:bookingDate,start_time:time(start),end_time:time(end),surat_status:status||'belum',surat_name:surat_name||null,surat_file_data:surat_file_data||null,surat_file_path:path,created_by:req.user.id,updated_by:req.user.id},include:{updatedBy:{select:{nama_lengkap:true}}}});broadcastChange();res.status(201).json({data:out(row)});}catch(err){logger.error('POST ruang rapat gagal',{error:err});res.status(500).json({message:'Gagal menyimpan booking ruang rapat.'});}});
router.put('/:id',requireRole(EDITOR_ROLES),async(req,res)=>{try{const id=Number(req.params.id);const b=req.body;const data={};if(b.title!==undefined){if(!validText(b.title,255))return res.status(400).json({message:'Agenda tidak valid.'});data.agenda=b.title.trim();}if(b.room!==undefined)data.room=b.room;if(b.pic!==undefined)data.pic=b.pic;if(b.pic_phone!==undefined){if(!validPhone(b.pic_phone))return res.status(400).json({message:'Nomor HP PIC tidak valid.'});data.pic_phone=b.pic_phone.trim();}if(b.date!==undefined)data.booking_date=date(b.date);if(b.start!==undefined)data.start_time=time(b.start);if(b.end!==undefined)data.end_time=time(b.end);if(b.status!==undefined)data.surat_status=b.status;if(b.surat_name!==undefined)data.surat_name=b.surat_name;if(b.surat_file_data!==undefined){if(!validFile(b.surat_file_data))return res.status(400).json({message:'Dokumen surat tidak valid.'});data.surat_file_data=b.surat_file_data||null;if(b.surat_file_data)data.surat_file_path=await saveDataUrl(b.surat_file_data,b.surat_name,'ruang-rapat');}if(data.room&&!ROOMS.includes(data.room))return res.status(400).json({message:'Ruangan tidak valid.'});if(data.surat_status&&!STATUS.includes(data.surat_status))return res.status(400).json({message:'Status surat tidak valid.'});if(data.pic!==undefined&&!validText(data.pic,150))return res.status(400).json({message:'Nama PIC tidak valid.'});if(data.booking_date||data.start_time||data.end_time){const current=await prisma.ruangRapat.findUnique({where:{id}});if(!current)return res.status(404).json({message:'Booking tidak ditemukan.'});const room=data.room??current.room, bd=data.booking_date??current.booking_date, st=data.start_time??current.start_time, et=data.end_time??current.end_time;if(et<=st)return res.status(400).json({message:'Jam selesai harus lebih besar dari jam mulai.'});const conflict=await prisma.ruangRapat.findFirst({where:{id:{not:id},room,booking_date:bd,start_time:{lt:et},end_time:{gt:st}}});if(conflict)return res.status(409).json({message:'Ruangan sudah dibooking pada waktu tersebut.'});}data.updated_by=req.user.id;const row=await prisma.ruangRapat.update({where:{id},data,include:{updatedBy:{select:{nama_lengkap:true}}}});broadcastChange();res.json({data:out(row)});}catch(err){if(err.code==='P2025')return res.status(404).json({message:'Booking tidak ditemukan.'});logger.error('PUT ruang rapat gagal',{error:err});res.status(500).json({message:'Gagal memperbarui booking.'});}});
router.delete('/:id',requireRole(EDITOR_ROLES),async(req,res)=>{try{await prisma.ruangRapat.delete({where:{id:Number(req.params.id)}});broadcastChange();res.json({message:'Booking dibatalkan.'});}catch(err){if(err.code==='P2025')return res.status(404).json({message:'Booking tidak ditemukan.'});logger.error('DELETE ruang rapat gagal',{error:err});res.status(500).json({message:'Gagal membatalkan booking.'});}});
module.exports=router;
